/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-17 02:57:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.salas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class salas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Cartelera - Salas de Cine</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\" crossorigin=\"anonymous\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Tu CSS debe ir después para poder sobrescribir estilos de Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/salas.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Definición del contexto -->\r\n");
      out.write("<script>\r\n");
      out.write("    const contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Script logout -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logout.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"encabezado\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"container d-flex justify-content-between align-items-center py-3\">\r\n");
      out.write("\t\t\t<div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("\t\t\t\t<img src=\"https://cdn-icons-png.flaticon.com/512/744/744922.png\"\r\n");
      out.write("\t\t\t\t\talt=\"Logo cine\" style=\"width: 40px;\">\r\n");
      out.write("\t\t\t\t<h1 class=\"titulo-pagina m-0\">Cine</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"btn-logout\">Cerrar Sesión</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- NAVBAR -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- CARTELERA -->\r\n");
      out.write("\t<div class=\"cartelera my-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- CARRUSEL DE PELÍCULAS -->\r\n");
      out.write("\t\t<div id=\"carouselExampleRide\" class=\"carousel slide mx-auto\"\r\n");
      out.write("\t\t\tdata-bs-ride=\"carousel\" style=\"max-width: 1050px;\">\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/5.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-block w-100\" alt=\"Minecraft\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/6.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-block w-100\" alt=\"Blanca Nieves\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/7.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-block w-100\" alt=\"Rescate Implacable\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/8.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-block w-100\" alt=\"Lilo y Stich\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-bs-target=\"#carouselExampleRide\" data-bs-slide=\"prev\">\r\n");
      out.write("\t\t\t\t<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"visually-hidden\">Anterior</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-bs-target=\"#carouselExampleRide\" data-bs-slide=\"next\">\r\n");
      out.write("\t\t\t\t<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"visually-hidden\">Siguiente</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Miniaturas clickeables -->\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"peliculas my-4 d-flex gap-4 justify-content-center flex-wrap\">\r\n");
      out.write("\t\t\t<div class=\"pelicula text-center\">\r\n");
      out.write("\t\t\t\t<a href=\"sala1.jsp\"> \r\n");
      out.write("\t\t\t\t\t\t<img src=\"https://static.cinemarkhoyts.com.ar/Images/Posters/362b0b9682619abc4e9c1061663aedb1.jpg?v=00002541\"\r\n");
      out.write("\t\t\t\t\t alt=\"Minecraft\" class=\"pelicula-img\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"titulo mt-2\">MINECRAFT</div>\r\n");
      out.write("\t\t\t\t<div class=\"estreno text-danger fw-bold\">ESTRENO</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pelicula text-center\">\r\n");
      out.write("\t\t\t\t<a href=\"sala2.jsp\"> \r\n");
      out.write("\t\t\t\t\t<img src=\"https://static.cinemarkhoyts.com.ar/Images/Posters/e22b65a127e28c40f3430181ee0c20be.jpg?v=00002552\"\r\n");
      out.write("\t\t\t\t\t alt=\"Blanca Nieves\" class=\"pelicula-img\"/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"titulo mt-2\">BLANCA NIEVES</div>\r\n");
      out.write("\t\t\t\t<div class=\"estreno text-danger fw-bold\">ESTRENO</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pelicula text-center\">\r\n");
      out.write("\t\t\t\t<a href=\"sala3.jsp\"> \r\n");
      out.write("\t\t\t\t\t<img src=\"https://static.cinemarkhoyts.com.ar/Images/Posters/533706b4add9a0023dfd656f7b23fb94.jpg?v=00002552\"\r\n");
      out.write("\t\t\t\t\t alt=\"Rescate\" class=\"pelicula-img\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"titulo mt-2\">RESCATE IMPLACABLE</div>\r\n");
      out.write("\t\t\t\t<div class=\"estreno text-danger fw-bold\">ESTRENO</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pelicula text-center\">\r\n");
      out.write("\t\t\t\t<a href=\"sala4.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"https://sacnkprodarcms.blob.core.windows.net/content/posters/HO00010245.jpg\"\r\n");
      out.write("\t\t\t\t\t alt=\"Lilo\" class=\"pelicula-img\"/>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"titulo mt-2\">LILO Y STICH</div>\r\n");
      out.write("\t\t\t\t<div class=\"estreno text-danger fw-bold\">ESTRENO</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS de Bootstrap -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Script logout si lo necesitas -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logout.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
