/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-04-11 13:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CompraForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <title>Selección de Butacas</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("\r\n");
      out.write("            margin: 0;\r\n");
      out.write("\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("\r\n");
      out.write("            background-color: #eee;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .left {\r\n");
      out.write("\r\n");
      out.write("            flex: 2;\r\n");
      out.write("\r\n");
      out.write("            padding-right: 40px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .right {\r\n");
      out.write("\r\n");
      out.write("            flex: 1;\r\n");
      out.write("\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("\r\n");
      out.write("            box-shadow: 0 0 5px #ccc;\r\n");
      out.write("\r\n");
      out.write("            height: fit-content;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("\r\n");
      out.write("            text-align: center;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .screen {\r\n");
      out.write("\r\n");
      out.write("            margin: 10px auto 20px;\r\n");
      out.write("\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("\r\n");
      out.write("            background-color: #ccc;\r\n");
      out.write("\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("            width: 80%;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .seating {\r\n");
      out.write("\r\n");
      out.write("            display: grid;\r\n");
      out.write("\r\n");
      out.write("            grid-template-columns: repeat(24, 30px);\r\n");
      out.write("\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .seat {\r\n");
      out.write("\r\n");
      out.write("            width: 28px;\r\n");
      out.write("\r\n");
      out.write("            height: 28px;\r\n");
      out.write("\r\n");
      out.write("            background-color: white;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("\r\n");
      out.write("            line-height: 28px;\r\n");
      out.write("\r\n");
      out.write("            text-align: center;\r\n");
      out.write("\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .seat.selected {\r\n");
      out.write("\r\n");
      out.write("            background-color: #ffeb3b;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .legend {\r\n");
      out.write("\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .legend-item {\r\n");
      out.write("\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("            align-items: center;\r\n");
      out.write("\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .legend-box {\r\n");
      out.write("\r\n");
      out.write("            width: 20px;\r\n");
      out.write("\r\n");
      out.write("            height: 20px;\r\n");
      out.write("\r\n");
      out.write("            margin-right: 6px;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .your-seat { background-color: #ffeb3b; }\r\n");
      out.write("\r\n");
      out.write("        .available { background-color: white; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .movie-info img {\r\n");
      out.write("\r\n");
      out.write("            width: 100%;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .movie-info h3 {\r\n");
      out.write("\r\n");
      out.write("            margin: 10px 0 5px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .summary {\r\n");
      out.write("\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .summary p {\r\n");
      out.write("\r\n");
      out.write("            margin: 6px 0;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .summary strong {\r\n");
      out.write("\r\n");
      out.write("            display: block;\r\n");
      out.write("\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .button-group {\r\n");
      out.write("\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("\r\n");
      out.write("            display: flex;\r\n");
      out.write("\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("\r\n");
      out.write("            border: none;\r\n");
      out.write("\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .btn-back {\r\n");
      out.write("\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .btn-next {\r\n");
      out.write("\r\n");
      out.write("            background-color: #ffe000;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .timer {\r\n");
      out.write("\r\n");
      out.write("            background-color: #eee;\r\n");
      out.write("\r\n");
      out.write("            text-align: right;\r\n");
      out.write("\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    let selectedSeats = [];\r\n");
      out.write("\r\n");
      out.write("    function toggleSeat(seat) {\r\n");
      out.write("        const number = seat.textContent;\r\n");
      out.write("        const row = seat.title.split(',')[0].split(' ')[1];\r\n");
      out.write("        const seatId = row + '-' + number;\r\n");
      out.write("\r\n");
      out.write("        // Si el asiento ya está seleccionado, se deselecciona\r\n");
      out.write("        if (seat.classList.contains(\"selected\")) {\r\n");
      out.write("            seat.classList.remove(\"selected\");\r\n");
      out.write("            selectedSeats = [];\r\n");
      out.write("        } else {\r\n");
      out.write("            // Si ya hay un asiento seleccionado, lo deseleccionamos\r\n");
      out.write("            const allSeats = document.querySelectorAll(\".seat.selected\");\r\n");
      out.write("            allSeats.forEach(s => s.classList.remove(\"selected\"));\r\n");
      out.write("\r\n");
      out.write("            selectedSeats = [seatId];\r\n");
      out.write("            seat.classList.add(\"selected\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        updateSummary();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function updateSummary() {\r\n");
      out.write("        const count = selectedSeats.length;\r\n");
      out.write("        const price = 6300; // precio por entrada\r\n");
      out.write("        const total = count * price;\r\n");
      out.write("        const serviceFee = count > 0 ? 1000 : 0;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"selected-count\").innerText = count;\r\n");
      out.write("        document.getElementById(\"selected-list\").innerText = selectedSeats.join(', ');\r\n");
      out.write("        document.getElementById(\"subtotal\").innerText = `$${total}`;\r\n");
      out.write("        document.getElementById(\"fee\").innerText = `$${serviceFee}`;\r\n");
      out.write("        document.getElementById(\"total\").innerText = `$${total + serviceFee}`;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"left\">\r\n");
      out.write("\r\n");
      out.write("        <h3>HOLA CLIENTE<br>Seleccioná tus butacas:</h3>\r\n");
      out.write("\r\n");
      out.write("        <p style=\"text-align:center; font-size: 13px; margin-bottom: 10px;\">\r\n");
      out.write("\r\n");
      out.write("            Hacé click sobre una ubicación disponible. Esta pantalla es una referencia y no representa distancias reales.\r\n");
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"screen\">PANTALLA</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"seating\">\r\n");
      out.write("\r\n");
      out.write("            ");


                char[] filas = "ABCDEFGHIJKL".toCharArray();

                for (int i = 0; i < filas.length; i++) {

                    for (int col = 1; col <= 10; col++) {

            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"seat\" onclick=\"toggleSeat(this)\" title=\"Fila ");
      out.print( filas[i] );
      out.write(", Asiento ");
      out.print( col );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.print( col );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            ");


                    }

                }

            
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"legend\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"legend-item\"><div class=\"legend-box your-seat\"></div> Tus butacas</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"legend-item\"><div class=\"legend-box available\"></div> Disponible</div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"movie-info\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"https://i.imgur.com/6XvZ5Vb.jpeg\" alt=\"mineccraft\">\r\n");
      out.write("\r\n");
      out.write("            <h3>Minecraft</h3>\r\n");
      out.write("\r\n");
      out.write("            <p>CASTELLANO 2D</p>\r\n");
      out.write("\r\n");
      out.write("            <p><strong>HOYTS MORENO - SALA 5</strong><br>AV. VICTORICA 1128, NINE SHOPPING<br>VIERNES 11 ABRIL 14:30</p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"summary\">\r\n");
      out.write("\r\n");
      out.write("            <p><strong><span id=\"selected-count\">0</span> ENTRADAS</strong></p>\r\n");
      out.write("\r\n");
      out.write("            <p><small>(BUTACAS: <span id=\"selected-list\">Ninguna</span>)</small></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p>Subtotal: <span id=\"subtotal\">$0</span></p>\r\n");
      out.write("\r\n");
      out.write("            <p>Cargo por servicio Entradas: <span id=\"fee\">$0</span></p>\r\n");
      out.write("\r\n");
      out.write("            <p>Cargo por servicio Candy: <span>$0</span></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p><strong>TOTAL: <span id=\"total\">$0</span></strong></p>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"button-group\">\r\n");
      out.write("\r\n");
      out.write("            <button class=\"btn btn-back\" ><a href=\"salas.jsp\" >VOLVER</button></a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"btn btn-next\"><a href=\"MetodoDePago.jsp\" >SIGUIENTE</button></a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\t\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
